name = "Endatabas"
uuid = "3c24e884-fd8b-4642-9948-3255f4665db5"
authors = ["contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
